package org.goolgeapi.keyword.research;

public enum ResearchConstants {
	CPCRANGE, RANKINFO, SCRAPPERCONFIGFORADCOUNT, SCRAPPERCONFIGFORURL, SCRAPPERCONFIG, URLLIST, TOTALCOMPPAGES, REALCOMPPAGES, ADCOUNT;
}
